### ISSUE TITLE
Windows, deb, rpm, brew installers

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#115]
Orko currently requires manual installation and can be sensitive to JRE versions, amongst other things.  We need to produce proper installers for standalone deployment.

https://stackoverflow.com/questions/1378129/how-to-create-installers-with-maven

DEBs and RPMs should ideally be deployed to a suitable repo so they can be managed with `apt` etc.

Should deploy these artifacts to the GitHub release when doing a tag build.

A re-usable configurator application to allow a user to set up their exchange API keys would be nice too.

**Comment by badgerwithagun** [comment]
I have had good experiences with Tanuki Wrapper: https://wrapper.tanukisoftware.com/doc/english/introduction.html

That makes the installer bit the simple bit.

**Comment by kenibarwick** [comment]
https://nsis.sourceforge.io/Simple_tutorials

**Comment by kenibarwick** [comment]
(a) make sure/get installed a JRE
(b) Wrap the JAR as a window service so it runs on startup
 (c) register the windows service 
(d) provide a means to set up all the config settings

**Comment by badgerwithagun** [comment]
On Linux installs, it strikes me that there is a "right" way and a "wrong" way to go about this.  The "right" way is that all the application's dependencies _also_ are installed using the platform's package manager, so they exist as shared dependencies (https://wiki.debian.org/Java/MavenDebianHelper).

The "wrong" way is to bundle everything together along with a JRE and deploy that.

In the middle is to at least make sure that obvious prerequisites like the JRE are installed separately and bundle all the Java together.

**Comment by badgerwithagun** [comment]
##Windows

I've just spent an unprofitable few hours investigating Tanuki wrapper. They don't provide 64 bit Windows versions, and it does seem that the 32 bit version doesn't run on modern Windows at all (I've tried everything).  At the same time, it's not clear whether [building your own and distributing that](https://www.krenger.ch/blog/java-service-wrapper-3-5-37-for-windows-x64/) is in murky licensing territory.  Absent any more information, I think we need to give up on running on Windows as a service and leave it as an exercise for a savvy user if they want to do it themselves.

**Instead**, I suggest that for Windows users, we simply create an NSIS installer which runs the application in a command window, and guides through JRE setup if there's on JRE installed or it's too old a version. Maybe later add a little configurator/tray application.  The priority here is to get it running on Windows in as few clicks as possible so a user can try it out.

## *Nix

Tanuki wrapper _does_ work just fine on most *nix flavours.  I've created a WIP pull request which creates the wrapper artifacts automatically as part of the build. See #262.

However, I've not tried out actually running this stuff yet, and there's [my comment above](#issuecomment-467382203) about doing this the "right" way.

**Comment by badgerwithagun** [comment]
The project has kind of moved past this and now is focused on continuous cloud deployment and containerisation. Closing.
