### ISSUE TITLE
Redundant subscribe issue when route change

### ISSUE THREAD

**Issue by lowwor** [gruelbox/orko#394]
When you switch ticker, like currently in ltc and click btc, there will be three history change trigger (btc -> ltc -> btc)and result in three resubscribe. The latter two is redundant. 
Here I switch from ltc to eos.
![](https://user-images.githubusercontent.com/5444033/58603040-c7915400-82c1-11e9-993d-c9b99fc31487.png)
![](https://user-images.githubusercontent.com/5444033/58603046-cf50f880-82c1-11e9-9cdb-ad7e6eac9081.png)
Also, there is a redundant coin in the subscribedCoins.
![](https://user-images.githubusercontent.com/5444033/58603107-12ab6700-82c2-11e9-992e-cb0e9b3d90eb.png)
And, we need to fix the redundant resubscribe when switch from not coin route to coin route.

**Comment by badgerwithagun** [comment]
Confirmed. Easy to replicate.

**Comment by badgerwithagun** [comment]
Fixed in master
